### ISSUE TITLE
seens to be broken on st 3 build 3080

### ISSUE THREAD

**Issue by igarcez** [jugyo/SublimeColorSchemeSelector#11]
It used to work perfectly but now it seems broken, very nice extension by the way!

this errors occurs when I try to use the select color scheme command

```
ValueError: invalid literal for int() with base 16: 'OO'
reloading Packages/User/Preferences.sublime-settings
reloading Packages/User/Preferences.sublime-settings
reloading Packages/User/Preferences.sublime-settings
reloading Packages/User/Preferences.sublime-settings
Traceback (most recent call last):
  File "ColorHighlighter in /Users/ian/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package", line 896, in <lambda>
  File "ColorHighlighter in /Users/ian/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package", line 787, in on_g_settings_change
  File "ColorHighlighter in /Users/ian/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package", line 859, in set_scheme_view
  File "ColorHighlighter in /Users/ian/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package", line 539, in load
  File "ColorHighlighter in /Users/ian/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package", line 367, in get_cont_col
```

**Comment by igarcez** [comment]
I couldn't replicate this bug anymore, gonna close this issue for now
