### ISSUE TITLE
Not functioning in Sublime Text 3

### ISSUE THREAD

**Issue by sleeve** [jugyo/SublimeColorSchemeSelector#5]
This doesn't seem to be functioning in Sublime Text 3 b3028. The list of themes are never displayed in the Command Palette after selecting 'ColorSchemeSelector: Select Color Scheme' and when selecting 'ColorSchemeSelector: Random Color Theme' the following error is displayed in the console:

```
Traceback (most recent call last):
    File "X/random.py", line 249, in choice
  File "X/random.py", line 225, in _randbelow
ValueError: number of bits must be greater than zero

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/Sublime Text 3.app/Contents/MacOS/sublime_plugin.py", line 524, in run_
    return self.run(**args)
  File "/Users/xxxx/Library/Application Support/Sublime Text 3/Installed Packages/ColorSchemeSelector.sublime-package/ColorSchemeSelector.py", line 15, in run
  File "X/random.py", line 251, in choice
IndexError: Cannot choose from an empty sequence
```

**Comment by jugyo** [comment]
oh, I'll look at. BTW, is Sublime Text 3 good? I'm hesitate to move from 2 to 3.

**Comment by sleeve** [comment]
Thanks. 

Yeah its good but not that different from ST2. A lot of ST2 packages have issues running on ST3 but its getting better.

**Comment by pine2D** [comment]
The package is loaded fine with ST3 Build 3030. But only color schemes in `/Data/Packages/user/` is detected. I guess it's because the color schemes installed by Package Control are now located in `/Data/Installed Packages/` and zipped as .sublime-package files.

BTW, ST3's startup time is significantly faster. I'd recommend you give it a shot.

**Comment by ctf0** [comment]
works great on ST3 b.3059 ,also all the schemes are detected ,not only in user folder

**Comment by oxydron** [comment]
Doesn't working on 3208.
It doesn't appear com command pallete.
